export const DO_ONE_TURN = 'DO_ONE_TURN';
export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const WARN_ABOUT_COLLISION = 'WARN_ABOUT_COLLISION';
export const START_TIMER_RUN = 'START_TIMER_RUN';
export const STOP_TIMER_RUN = 'STOP_TIMER_RUN';
export const RESET_CARTS_COLLISIONS = 'RESET_CARTS_COLLISIONS';